import { displayAcceptance } from "../Accepted";
import Coinbase from "../Coinbase";
import ErrorMessage from "../ErrorMessage";
import KasLink from "../KasLink";
import LoadingMessage from "../LoadingMessage";
import PageTable from "../PageTable";
import Tooltip, { TooltipDisplayMode } from "../Tooltip";
import ArrowRight from "../assets/arrow-right.svg";
import Box from "../assets/box.svg";
import Info from "../assets/info.svg";
import { useBlockById } from "../hooks/useBlockById";
import { useTransactionsSearch } from "../hooks/useTransactionsSearch";
import { useVirtualChainBlueScore } from "../hooks/useVirtualChainBlueScore";
import FooterHelper from "../layout/FooterHelper";
import type { Route } from "./+types/blockdetails";
import dayjs from "dayjs";
import localeData from "dayjs/plugin/localeData";
import localizedFormat from "dayjs/plugin/localizedFormat";
import relativeTime from "dayjs/plugin/relativeTime";
import numeral from "numeral";
import React, { useEffect } from "react";
import { Link } from "react-router";

dayjs().locale("en");
dayjs.extend(relativeTime);
dayjs.extend(localeData);
dayjs.extend(localizedFormat);

export async function loader({ params }: Route.LoaderArgs) {
  const blockId = params.blockId;
  return { blockId };
}

export function meta({ params }: Route.LoaderArgs) {
  return [
    { title: `Kaspa Block ${params.blockId} | Kaspa Explorer` },
    {
      name: "description",
      content: "View Kaspa block details. Check transactions, miner, block hash, confirmations, and DAG links.",
    },
    { name: "keywords", content: "Kaspa block, blockchain explorer, block details, miner, DAG, transactions" },
  ];
}

export default function Blocks({ loaderData }: Route.ComponentProps) {
  const { data: block, isLoading, isError } = useBlockById(loaderData.blockId);
  const { data: inputTxs, refetch: fetchTransactions } = useTransactionsSearch(
    (block?.transactions.map((tx) => tx.verboseData.transactionId) || []).concat(
      block?.transactions.flatMap((tx) => tx.inputs.map((input) => input.previousOutpoint.transactionId)) || [],
    ),
    "",
    "light",
    false,
  );

  const { virtualChainBlueScore } = useVirtualChainBlueScore();

  useEffect(() => {
    if (block) {
      fetchTransactions();
    }
  }, [block]);

  useEffect(() => {
    if (block && inputTxs) {
      const cntNotAccepted = block.transactions
        .map((transaction) => getTxFromInputTxs(transaction.verboseData.transactionId)?.is_accepted ?? false)
        .filter((accepted) => !accepted).length;

      if (cntNotAccepted > 1) {
        const timeoutRefetch = setTimeout(() => fetchTransactions(), 2000);
        return () => {
          clearTimeout(timeoutRefetch);
        };
      }
    }
  }, [inputTxs]);

  const blockTime = dayjs(Number(block?.header.timestamp));
  if (isLoading) {
    return <LoadingMessage>Loading block</LoadingMessage>;
  }

  if (isError) {
    return (
      <ErrorMessage>
        Unable to load a block with hash
        <span className="text-gray-500"> {loaderData.blockId}</span>
      </ErrorMessage>
    );
  }

  const getTxFromInputTxs = (txId: string) => {
    for (const tx of inputTxs || []) {
      if (tx.transaction_id === txId) return tx;
    }
  };

  const getAddressFromOutpoint = (txId: string, outpointIndex: number) => {
    for (const tx of inputTxs || []) {
      if (tx.transaction_id === txId) {
        for (const output of tx.outputs || []) {
          if (output.index === outpointIndex) {
            return <KasLink linkType={"address"} to={output.script_public_key_address} shorten link mono />;
          }
        }
      }
    }
    return (
      <>
        <KasLink linkType={"transaction"} to={txId} shorten link mono />
        {` #${outpointIndex}`}
      </>
    );
  };
  return (
    <>
      <div className="grid w-full grid-cols-1 gap-x-18 gap-y-2 rounded-4xl bg-white p-4 text-left text-nowrap text-black sm:grid-cols-[auto_1fr] sm:p-8">
        <div className="flex flex-row items-center text-2xl sm:col-span-2">
          <Box className="mr-2 h-8 w-8" />
          Blocks details
        </div>
        <div className="mt-4 text-black sm:col-span-2">Main information</div>
        <FieldName
          name="Block Hash"
          infoText="A unique identifier for this block, generated by hashing its contents."
        />
        <FieldValue value={<KasLink linkType="block" copy to={loaderData.blockId} />} />
        <FieldName name="Blue score" infoText="Amount of the blue blocks so far." />
        <FieldValue value={block?.header.blueScore} />
        <FieldName name="Bits" infoText="Number of bits in the block." />
        <FieldValue value={block?.header.bits} />
        <FieldName name="Timestamp" infoText="The time when the block was created, set by the miner." />
        <FieldValue
          value={
            <div className="flex flex-col">
              <span>{blockTime.fromNow()}</span>
              <span className="text-gray-500">{blockTime.format("ll LTS")}</span>
            </div>
          }
        />
        <FieldName name="Version" infoText="Version of the block template." />
        <FieldValue value={block?.header.version} />
        <FieldName name="Is chain block" infoText="Indicates if this block is a part of the virtual chain." />
        <FieldValue value={block?.verboseData.isChainBlock ? "Yes" : "No"} />
        {/*horizontal rule*/}
        <div className={`my-4 h-[1px] bg-gray-100 sm:col-span-2`} />
        <div className="text-black sm:col-span-2">Connections</div>
        <FieldName name="Parents" infoText="Displays the parents of this block in the BlockDAG." />
        <FieldValue
          value={block?.header.parents[0].parentHashes.map((parentHash) => (
            <div>
              <KasLink linkType="block" link to={`${parentHash}`} mono />
            </div>
          ))}
        />
        <FieldName name="Children" infoText="Displays the children of this block in the BlockDAG." />
        <FieldValue
          value={block?.verboseData.childrenHashes.map((child) => (
            <div>
              <KasLink linkType="block" link to={`${child}`} mono />
            </div>
          ))}
        />
        <div className={`my-4 h-[1px] bg-gray-100 sm:col-span-2`} />
        <div className="text-black sm:col-span-2">Merkle and UTXO data</div>
        <FieldName name="Merkle root" infoText="A cryptographic hash that represents all transactions in the block." />
        <FieldValue value={block?.header.hashMerkleRoot} />
        <FieldName name="Accepted merkle root" infoText="Acceptance merkle root, used to verify the block." />
        <FieldValue value={block?.header.acceptedIdMerkleRoot} />
        <FieldName name="UTXO commitment" infoText="The block commitment to the UTXO set, used to verify the block." />
        <FieldValue value={block?.header.utxoCommitment} />
        <div className={`my-4 h-[1px] bg-gray-100 sm:col-span-2`} />
        <div className="flex flex-row items-start text-black sm:col-span-2">Difficulty and computation</div>
        <FieldName name="Nonce" infoText="A random number used to generate the block hash." />
        <FieldValue value={block?.header.nonce} />
        <FieldName name="DAA score" infoText="The count of all blocks ( red and blue ) in the network." />
        <FieldValue value={block?.header.daaScore} />
        <FieldName name="Blue work" infoText="The cumulative proof-of-work of all blue blocks." />
        <FieldValue value={block?.header.blueWork} />
        <div className={`my-4 h-[1px] bg-gray-100 sm:col-span-2`} />
        <div className="text-black sm:col-span-2">Additional data</div>
        <FieldName
          name="Pruning point"
          infoText="A reference block in the past of the BlockDAG, used to prune previous data."
        />
        <FieldValue value={<KasLink linkType="block" link to={block?.header.pruningPoint || ""} />} />
        {block?.extra?.minerInfo && (
          <>
            <FieldName
              name="Miner info"
              infoText="Miner address and free text field filled by the miner of this block."
            />
            <FieldValue
              value={
                <>
                  <div className="text-link">
                    <Link to={`/addresses/${block.extra.minerAddress}`}>{block.extra.minerAddress}</Link>
                  </div>
                  <div className="text-gray-500">{block.extra.minerInfo}</div>
                </>
              }
            />
          </>
        )}
      </div>
      <div className="flex flex-col w-full gap-x-18 gap-y-2 rounded-4xl bg-white p-4 text-left text-nowrap text-black sm:p-8">
        <div className="mt-4 mb-2 text-black sm:col-span-2">Transactions</div>
        <PageTable
          alignTop
          headers={["Transaction ID", "From", "", "To", "Amount", "Status"]}
          rows={
            block?.transactions.map((transaction) => [
              <KasLink linkType="transaction" to={transaction.verboseData.transactionId} link shorten mono />,
              <ul>
                {transaction.inputs.length > 0 ? (
                  transaction.inputs.map((input) => (
                    <li>
                      {getAddressFromOutpoint(input.previousOutpoint.transactionId, input.previousOutpoint.index)}
                    </li>
                  ))
                ) : (
                  <Coinbase />
                )}
              </ul>,
              <ArrowRight className="inline h-4 w-4" />,
              <ul>
                {transaction.outputs.map((output) => (
                  <li>
                    <KasLink
                      linkType="address"
                      to={output.verboseData.scriptPublicKeyAddress}
                      link
                      shorten
                      resolveName
                      mono
                    />
                  </li>
                ))}
              </ul>,
              <ul>
                {transaction.outputs.map((output) => (
                  <li>
                    {numeral(output.amount / 1_0000_0000).format("0,0.00[000000]")}
                    <span className="text-gray-500 text-nowrap"> KAS</span>
                  </li>
                ))}
              </ul>,
              <div className="flex flex-row gap-x-2 justfiy-start md:justify-end">
                {displayAcceptance(
                  getTxFromInputTxs(transaction.verboseData.transactionId)?.is_accepted ?? false,
                  virtualChainBlueScore
                    ? virtualChainBlueScore -
                        (getTxFromInputTxs(transaction.verboseData.transactionId)?.accepting_block_blue_score || 0)
                    : undefined,
                )}
              </div>,
            ]) || []
          }
        />
      </div>
      <FooterHelper icon={Box}>
        <span>
          A block is a secure, sequential record in the blockchain containing verified transactions, a unique hash, and
          a reference to the previous block, ensuring data integrity.
        </span>
      </FooterHelper>
    </>
  );
}

const FieldName = ({ name, infoText }: { name: string; infoText?: string }) => (
  <div className="flex flex-row items-start fill-gray-500 text-gray-500 sm:col-start-1">
    <div className="flex flex-row items-center">
      <Tooltip message={infoText || ""} display={TooltipDisplayMode.Hover} multiLine>
        <Info className="h-4 w-4" />
      </Tooltip>
      <span className="ms-1">{name}</span>
    </div>
  </div>
);

const FieldValue = ({ value }: { value: string | React.ReactNode }) => (
  <div className="break-all text-wrap">{value}</div>
);
