import ArrowRight from "../assets/arrow-right.svg";
import Box from "../assets/box.svg";
import Info from "../assets/info.svg";
import type { Route } from "./+types/blockdetails";
import dayjs from "dayjs";
import localeData from "dayjs/plugin/localeData";
import localizedFormat from "dayjs/plugin/localizedFormat";
import relativeTime from "dayjs/plugin/relativeTime";
import { Link } from "react-router";
import { Accepted } from "~/Accepted";
import ErrorMessage from "~/ErrorMessage";
import KasLink from "~/KasLink";
import LoadingMessage from "~/LoadingMessage";
import Tooltip from "~/Tooltip";
import { useBlockById } from "~/hooks/useBlockById";

dayjs().locale("en");
dayjs.extend(relativeTime);
dayjs.extend(localeData);
dayjs.extend(localizedFormat);

export async function loader({ params }: Route.LoaderArgs) {
  const blockId = params.blockId;
  return { blockId };
}

export function meta() {
  return [
    { title: "Kaspa Explorer - Blocks" },
    {
      name: "description",
      content:
        "Overview page of Kaspa Block Explorer, showcasing recent blocks, their details, and insights into the Kaspa blockchain.",
    },
  ];
}

export default function Blocks({ loaderData }: Route.ComponentProps) {
  const { data: block, isLoading, isError } = useBlockById(loaderData.blockId);
  const blockTime = dayjs(Number(block?.header.timestamp));
  if (isLoading) {
    return <LoadingMessage>Loading block</LoadingMessage>;
  }

  if (isError) {
    return (
      <ErrorMessage>
        Unable to load a block with hash
        <span className="text-gray-500"> {loaderData.blockId}</span>
      </ErrorMessage>
    );
  }

  return (
    <>
      <div className="grid w-full grid-cols-1 gap-x-18 gap-y-2 rounded-4xl bg-white p-4 text-left text-nowrap text-black sm:grid-cols-[auto_1fr] sm:p-8">
        <div className="flex flex-row items-center text-2xl sm:col-span-2">
          <Box className="mr-2 h-8 w-8" />
          Blocks details
        </div>
        <div className="mt-4 text-black sm:col-span-2">Main information</div>
        <FieldName
          name="Block Hash"
          infoText="A unique identifier for this block, generated by hashing its contents."
        />
        <FieldValue value={<KasLink linkType="block" copy to={loaderData.blockId} />} />
        <FieldName name="Blue score" infoText="TODO" />
        <FieldValue value={block?.header.blueScore} />
        <FieldName name="Bits" infoText="TODO" />
        <FieldValue value={block?.header.bits} />
        <FieldName name="Timestamp" infoText="The time when the block was created, set by the miner." />
        <FieldValue
          value={
            <div className="flex flex-col">
              <span>{blockTime.fromNow()}</span>
              <span className="text-sm text-gray-500">{blockTime.format("ll LTS")}</span>
            </div>
          }
        />
        <FieldName name="Version" infoText="TODO" />
        <FieldValue value={block?.header.version} />
        <FieldName name="Is chain block" infoText="Indicates if this block is a part of the virtual chain." />
        <FieldValue value={block?.verboseData.isChainBlock ? "Yes" : "No"} />
        {/*horizontal rule*/}
        <div className={`my-4 h-[1px] bg-gray-100 sm:col-span-2`} />
        <div className="text-black sm:col-span-2">Connections</div>
        <FieldName name="Parents" infoText="Displays the parents of this block in the BlockDAG." />
        <FieldValue
          value={block?.header.parents[0].parentHashes.map((parentHash) => (
            <div>
              <KasLink linkType="block" link to={`${parentHash}`} />
            </div>
          ))}
        />
        <FieldName name="Children" infoText="Displays the children of this block in the BlockDAG." />
        <FieldValue
          value={block?.verboseData.childrenHashes.map((child) => (
            <div>
              <KasLink linkType="block" link to={`${child}`} />
            </div>
          ))}
        />
        <div className={`my-4 h-[1px] bg-gray-100 sm:col-span-2`} />
        <div className="text-black sm:col-span-2">Merkle and UTXO data</div>
        <FieldName name="Merkle root" infoText="TODO" />
        <FieldValue value={block?.header.hashMerkleRoot} />
        <FieldName name="Accepted merkle root" infoText="TODO" />
        <FieldValue value={block?.header.acceptedIdMerkleRoot} />
        <FieldName name="UTXO commitment" infoText="TODO" />
        <FieldValue value={block?.header.utxoCommitment} />
        <div className={`my-4 h-[1px] bg-gray-100 sm:col-span-2`} />
        <div className="flex flex-row items-start text-black sm:col-span-2">Difficulty and computation</div>
        <FieldName name="Nonce" infoText="A random number used to generate the block hash." />
        <FieldValue value={block?.header.nonce} />
        <FieldName name="DAA score" infoText="The count of all blocks ( red and blue ) in the network" />
        <FieldValue value={block?.header.daaScore} />
        <FieldName name="Blue work" infoText="TODO" />
        <FieldValue value={block?.header.blueWork} />
        <div className={`my-4 h-[1px] bg-gray-100 sm:col-span-2`} />
        <div className="text-black sm:col-span-2">Additional data</div>
        <FieldName
          name="Pruning point"
          infoText="A reference block in the past of the BlockDAG, used to prune previous data."
        />
        <FieldValue value={<KasLink linkType="block" link to={block?.header.pruningPoint || ""} />} />
        {block?.extra?.minerInfo && (
          <>
            <FieldName
              name="Miner info"
              infoText="Miner address and free text field filled by the miner of this block."
            />
            <FieldValue
              value={
                <>
                  <div className="text-link">
                    <Link to={`/addresses/${block.extra.minerAddress}`}>{block.extra.minerAddress}</Link>
                  </div>
                  <div className="text-sm text-gray-500">{block.extra.minerInfo}</div>
                </>
              }
            />
          </>
        )}
      </div>
      <div className="grid w-full grid-cols-1 gap-x-18 gap-y-2 overflow-x-auto rounded-4xl bg-white p-4 text-left text-nowrap text-black sm:p-8">
        <div className="mt-4 mb-2 text-black sm:col-span-2">Transactions</div>

        <div className="grid w-full grid-cols-[auto_2fr_auto_2fr_auto_auto] gap-x-4 gap-y-2">
          <div className="text-gray-500">TX-ID</div>
          <div className="col-span-2 text-gray-500">From</div>
          <div className="text-gray-500">To</div>
          <div className="text-gray-500">Status</div>
          <div className="text-right text-gray-500">Amount</div>

          <div className="col-span-6 h-[1px] bg-gray-100" />
          <div className="text-black">123b12....28b12b318293</div>
          <div className="text-link text-sm">
            kaspa:qzyzhlkd8thwy...4h6mtfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
          </div>
          <div className="flex items-center fill-black text-black">
            <ArrowRight className="h-5 w-5" />
          </div>
          <div className="text-link text-sm">
            kaspa:qzyzhlkd8thwy...4h6mtfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
          </div>
          <div className="text-success">
            <Accepted />
          </div>
          <div className="text-black">
            1234<span className="text-sm text-gray-500"> KAS</span>
          </div>

          <div className="col-span-6 h-[1px] bg-gray-100" />
          <div className="text-black">123b12....28b12b318293</div>
          <div className="text-link text-sm">
            kaspa:qzyzhlkd8thwy...4h6mtfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
          </div>
          <div className="flex items-center fill-black text-black">
            <ArrowRight className="h-5 w-5" />
          </div>
          <div className="text-link text-sm">
            kaspa:qzyzhlkd8thwy...4h6mtfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
          </div>
          <div className="text-success">
            <Accepted />
          </div>
          <div className="text-black">
            1234<span className="text-sm text-gray-500"> KAS</span>
          </div>
          <div className="col-span-6 h-[1px] bg-gray-100" />
          <div className="text-black">123b12....28b12b318293</div>
          <div className="text-link text-sm">
            kaspa:qzyzhlkd8thwy...4h6mtfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
          </div>
          <div className="flex items-center fill-black text-black">
            <ArrowRight className="h-5 w-5" />
          </div>
          <div className="text-link text-sm">
            kaspa:qzyzhlkd8thwy...4h6mtfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
          </div>
          <div className="text-success">
            <Accepted />
          </div>
          <div className="text-black">
            1234<span className="text-sm text-gray-500"> KAS</span>
          </div>
          <div className="col-span-6 h-[1px] bg-gray-100" />
          <div className="text-black">123b12....28b12b318293</div>
          <div className="text-link text-sm">
            kaspa:qzyzhlkd8thwy...4h6mtfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
          </div>
          <div className="flex items-center fill-black text-black">
            <ArrowRight className="h-5 w-5" />
          </div>
          <div className="text-link text-sm">
            kaspa:qzyzhlkd8thwy...4h6mtfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
          </div>
          <div className="text-success">
            <Accepted />
          </div>
          <div className="text-black">
            1234<span className="text-sm text-gray-500"> KAS</span>
          </div>
          <div className="col-span-6 h-[1px] bg-gray-100" />
          <div className="text-black">123b12....28b12b318293</div>
          <div className="text-link text-sm">
            kaspa:qzyzhlkd8thwy...4h6mtfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
          </div>
          <div className="flex items-center fill-black text-black">
            <ArrowRight className="h-5 w-5" />
          </div>
          <div className="text-link text-sm">
            kaspa:qzyzhlkd8thwy...4h6mtfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
            <br />
            kaspa:qzyzhlkd8thwywu...tfj222rtgcn
          </div>
          <div className="text-success">
            <Accepted />
          </div>
          <div className="text-black">
            1234<span className="text-sm text-gray-500"> KAS</span>
          </div>
        </div>
      </div>
    </>
  );
}

const FieldName = ({ name, infoText }: { name: string; infoText?: string }) => (
  <div className="flex flex-row items-start fill-gray-500 text-gray-500 sm:col-start-1">
    <div className="flex flex-row items-center">
      <Tooltip message={infoText || ""} hover duration={2000}>
        <Info className="h-4 w-4" />
      </Tooltip>
      <span className="ms-1">{name}</span>
    </div>
  </div>
);

const FieldValue = ({ value }: { value: string | React.ReactNode }) => <span className="overflow-hidden">{value}</span>;
